FROM gfelbing/debian-stable
RUN apt-get -y update \\&\\& apt-get -y upgrade \\&\\& apt-get -y install texlive \\&\\& apt-get -y clean
ADD $PANDOC /tmp
RUN dpkg -i /tmp/$PANDOC \\&\\& ln -s /dev/stdout /dev/pandoc.pdf
