FROM gfelbing/debian-stable
RUN apt-get -y update \\&\\& apt-get -y upgrade \\&\\& apt-get -y install --no-install-recommends texlive-full \\&\\& apt-get -y clean
ADD $PANDOC /tmp
RUN dpkg -i /tmp/$PANDOC
