FROM gfelbing/debian-stable
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install python-pip python-dev
RUN pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

